package metadata

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"main/utils/structs"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"main/internal/core"
	"main/internal/utils"

	"github.com/zhaarey/go-mp4tag"
)

func WriteCover(sanAlbumFolder, name string, url string) (string, error) {
	covPath := filepath.Join(sanAlbumFolder, name+"."+core.Config.CoverFormat)
	if core.Config.CoverFormat == "original" {
		ext := strings.Split(url, "/")[len(strings.Split(url, "/"))-2]
		ext = ext[strings.LastIndex(ext, ".")+1:]
		covPath = filepath.Join(sanAlbumFolder, name+"."+ext)
	}
	exists, err := utils.FileExists(covPath)
	if err != nil {
		return "", err
	}
	if exists {
		_ = os.Remove(covPath)
	}
	if core.Config.CoverFormat == "png" {
		re := regexp.MustCompile(`\{w\}x\{h\}`)
		parts := re.Split(url, 2)
		url = parts[0] + "{w}x{h}" + strings.Replace(parts[1], ".jpg", ".png", 1)
	}
	url = strings.Replace(url, "{w}x{h}", core.Config.CoverSize, 1)
	if core.Config.CoverFormat == "original" {
		url = strings.Replace(url, "is1-ssl.mzstatic.com/image/thumb", "a5.mzstatic.com/us/r1000/0", 1)
		url = url[:strings.LastIndex(url, "/")]
	}
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
	do, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer do.Body.Close()
	if do.StatusCode != http.StatusOK {
		return "", errors.New(do.Status)
	}
	f, err := os.Create(covPath)
	if err != nil {
		return "", err
	}
	defer f.Close()
	_, err = io.Copy(f, do.Body)
	if err != nil {
		return "", err
	}
	return covPath, nil
}

func WriteLyrics(sanAlbumFolder, filename string, lrc string) error {
	lyricspath := filepath.Join(sanAlbumFolder, filename)
	f, err := os.Create(lyricspath)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(lrc)
	if err != nil {
		return err
	}
	return nil
}

var (
	mp4LyricsTimestampPattern = regexp.MustCompile(
		`(\[[0-9]{1,3}:[0-9]{2}([.:][0-9]{1,3})?\]|<[0-9]{1,3}:[0-9]{2}([.:][0-9]{1,3})?>)`,
	)
	mp4LyricsMetadataPattern = regexp.MustCompile(
		`(?i)^\[(ar|al|ti|by|offset|re|ve|length|id|au|su|la|tool):`,
	)
)

func cleanEmbeddedMP4Lyrics(value string) string {
	raw := strings.TrimSpace(value)
	if raw == "" {
		return ""
	}

	if strings.Contains(strings.ToLower(raw), "<tt") {
		if plain := cleanTTMLLyrics(raw); plain != "" {
			return plain
		}
	}

	raw = strings.ReplaceAll(raw, "\r\n", "\n")
	raw = strings.ReplaceAll(raw, "\r", "\n")
	lines := make([]string, 0)
	for _, rawLine := range strings.Split(raw, "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || mp4LyricsMetadataPattern.MatchString(line) {
			continue
		}
		line = mp4LyricsTimestampPattern.ReplaceAllString(line, "")
		line = strings.TrimSpace(line)
		if line != "" {
			lines = append(lines, line)
		}
	}
	return strings.Join(lines, "\n")
}

func cleanTTMLLyrics(raw string) string {
	decoder := xml.NewDecoder(strings.NewReader(raw))
	var current strings.Builder
	var fallback strings.Builder
	lines := make([]string, 0)
	inParagraph := false
	skipDepth := 0

	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return ""
		}

		switch item := token.(type) {
		case xml.StartElement:
			name := strings.ToLower(item.Name.Local)
			if skipDepth > 0 {
				skipDepth++
				continue
			}
			if name == "head" ||
				name == "metadata" ||
				name == "translations" ||
				name == "translation" ||
				name == "transliterations" ||
				name == "transliteration" {
				skipDepth = 1
				continue
			}
			if name == "p" {
				current.Reset()
				inParagraph = true
			}
		case xml.EndElement:
			if skipDepth > 0 {
				skipDepth--
				continue
			}
			if strings.EqualFold(item.Name.Local, "p") && inParagraph {
				line := strings.TrimSpace(current.String())
				if line != "" {
					lines = append(lines, line)
				}
				current.Reset()
				inParagraph = false
			}
		case xml.CharData:
			if skipDepth > 0 {
				continue
			}
			text := strings.Join(strings.Fields(string(item)), " ")
			if text == "" {
				continue
			}
			if inParagraph {
				if current.Len() > 0 {
					current.WriteByte(' ')
				}
				current.WriteString(text)
			} else {
				if fallback.Len() > 0 {
					fallback.WriteByte(' ')
				}
				fallback.WriteString(text)
			}
		}
	}

	if len(lines) > 0 {
		return strings.Join(lines, "\n")
	}
	return strings.TrimSpace(fallback.String())
}

func WriteMP4Tags(trackPath, lrc, qobuzDesc string, meta *structs.AutoGenerated, trackNum, trackTotal int, coverPaths ...string) (err error) {
	index := trackNum - 1

	t := &mp4tag.MP4Tags{
		Title:      meta.Data[0].Relationships.Tracks.Data[index].Attributes.Name,
		TitleSort:  meta.Data[0].Relationships.Tracks.Data[index].Attributes.Name,
		Artist:     meta.Data[0].Relationships.Tracks.Data[index].Attributes.ArtistName,
		ArtistSort: meta.Data[0].Relationships.Tracks.Data[index].Attributes.ArtistName,
		Custom: map[string]string{
			"PERFORMER":   meta.Data[0].Relationships.Tracks.Data[index].Attributes.ArtistName,
			"RELEASETIME": meta.Data[0].Relationships.Tracks.Data[index].Attributes.ReleaseDate,
			"ISRC":        meta.Data[0].Relationships.Tracks.Data[index].Attributes.Isrc,
			"LABEL":       meta.Data[0].Attributes.RecordLabel,
			"UPC":         meta.Data[0].Attributes.Upc,
		},
		Composer:     meta.Data[0].Relationships.Tracks.Data[index].Attributes.ComposerName,
		ComposerSort: meta.Data[0].Relationships.Tracks.Data[index].Attributes.ComposerName,
		Date:         meta.Data[0].Attributes.ReleaseDate,
		CustomGenre:  meta.Data[0].Relationships.Tracks.Data[index].Attributes.GenreNames[0],
		Copyright:    meta.Data[0].Attributes.Copyright,
		Publisher:    meta.Data[0].Attributes.RecordLabel,
		Lyrics:       cleanEmbeddedMP4Lyrics(lrc),
	}

	if len(coverPaths) > 0 && coverPaths[0] != "" {
		coverData, err := os.ReadFile(coverPaths[0])
		if err != nil {
			return err
		}
		if len(coverData) < 4 {
			return errors.New("cover artwork is empty or truncated")
		}
		coverFormat, err := detectMP4CoverImageType(coverData)
		if err != nil {
			return err
		}
		t.Pictures = []*mp4tag.MP4Picture{{
			Format: coverFormat,
			Data:   coverData,
		}}
	}

	var appleDesc string
	var finalComment string

	if meta.Data[0].Attributes.EditorialNotes != nil && meta.Data[0].Attributes.EditorialNotes.Standard != "" {
		reHTML := regexp.MustCompile("<[^>]*>")
		textWithoutHTML := reHTML.ReplaceAllString(meta.Data[0].Attributes.EditorialNotes.Standard, "")
		reNewlines := regexp.MustCompile(`\n{2,}`)
		appleDesc = strings.TrimSpace(reNewlines.ReplaceAllString(textWithoutHTML, "\n"))
	}

	cleanedQobuzDesc := qobuzDesc

	if appleDesc != "" {
		finalComment = "©Copyright Apple Music：" + appleDesc
	}
	if cleanedQobuzDesc != "" {
		if finalComment != "" {
			finalComment += "\n——————————————————\n"
		}
		finalComment += "©Copyright Qobuz：" + cleanedQobuzDesc
	}

	if finalComment != "" {
		t.Comment = finalComment
	}

	if !strings.Contains(meta.Data[0].ID, "pl.") {
		albumID, err := strconv.ParseUint(meta.Data[0].ID, 10, 32)
		if err == nil {
			t.ItunesAlbumID = int32(albumID)
		}
	}

	if len(meta.Data[0].Relationships.Artists.Data) > 0 {
		if len(meta.Data[0].Relationships.Tracks.Data[index].Relationships.Artists.Data) > 0 {
			artistID, err := strconv.ParseUint(meta.Data[0].Relationships.Tracks.Data[index].Relationships.Artists.Data[0].ID, 10, 32)
			if err == nil {
				t.ItunesArtistID = int32(artistID)
			}
		}
	}

	if strings.Contains(meta.Data[0].ID, "pl.") && !core.Config.UseSongInfoForPlaylist {
		t.DiscNumber = 1
		t.DiscTotal = 1
		t.TrackNumber = int16(trackNum)
		t.TrackTotal = int16(trackTotal)
		t.Album = meta.Data[0].Attributes.Name
		t.AlbumSort = meta.Data[0].Attributes.Name
		t.AlbumArtist = meta.Data[0].Attributes.ArtistName
		t.AlbumArtistSort = meta.Data[0].Attributes.ArtistName
	} else if strings.Contains(meta.Data[0].ID, "pl.") && core.Config.UseSongInfoForPlaylist {
		t.DiscNumber = int16(meta.Data[0].Relationships.Tracks.Data[index].Attributes.DiscNumber)
		t.DiscTotal = int16(meta.Data[0].Relationships.Tracks.Data[trackTotal-1].Attributes.DiscNumber)
		t.TrackNumber = int16(meta.Data[0].Relationships.Tracks.Data[index].Attributes.TrackNumber)
		t.TrackTotal = int16(trackTotal)
		t.Album = meta.Data[0].Relationships.Tracks.Data[index].Attributes.AlbumName
		t.AlbumSort = meta.Data[0].Relationships.Tracks.Data[index].Attributes.AlbumName
		t.AlbumArtist = meta.Data[0].Relationships.Tracks.Data[index].Relationships.Albums.Data[0].Attributes.ArtistName
		t.AlbumArtistSort = meta.Data[0].Relationships.Tracks.Data[index].Relationships.Albums.Data[0].Attributes.ArtistName
	} else {
		currentDisc := meta.Data[0].Relationships.Tracks.Data[index].Attributes.DiscNumber
		maxDisc := 0
		tracksOnDisc := 0
		for _, tr := range meta.Data[0].Relationships.Tracks.Data {
			if tr.Attributes.DiscNumber > maxDisc {
				maxDisc = tr.Attributes.DiscNumber
			}
			if tr.Attributes.DiscNumber == currentDisc {
				tracksOnDisc++
			}
		}

		t.DiscNumber = int16(meta.Data[0].Relationships.Tracks.Data[index].Attributes.DiscNumber)
		t.DiscTotal = int16(maxDisc)
		t.TrackNumber = int16(meta.Data[0].Relationships.Tracks.Data[index].Attributes.TrackNumber)
		t.TrackTotal = int16(tracksOnDisc)
		t.Album = meta.Data[0].Relationships.Tracks.Data[index].Attributes.AlbumName
		t.AlbumSort = meta.Data[0].Relationships.Tracks.Data[index].Attributes.AlbumName
		t.AlbumArtist = meta.Data[0].Attributes.ArtistName
		t.AlbumArtistSort = meta.Data[0].Attributes.ArtistName
	}

	if meta.Data[0].Relationships.Tracks.Data[index].Attributes.ContentRating == "explicit" {
		t.ItunesAdvisory = mp4tag.ItunesAdvisoryExplicit
	} else if meta.Data[0].Relationships.Tracks.Data[index].Attributes.ContentRating == "clean" {
		t.ItunesAdvisory = mp4tag.ItunesAdvisoryClean
	} else {
		t.ItunesAdvisory = mp4tag.ItunesAdvisoryNone
	}

	return writeMP4TagsOnePass(trackPath, t)
}

func detectMP4CoverImageType(data []byte) (mp4tag.ImageType, error) {
	if len(data) >= 8 &&
		bytes.Equal(
			data[:8],
			[]byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A},
		) {
		return mp4tag.ImageTypePNG, nil
	}
	if len(data) >= 3 &&
		bytes.Equal(data[:3], []byte{0xFF, 0xD8, 0xFF}) {
		return mp4tag.ImageTypeJPEG, nil
	}
	return mp4tag.ImageTypeAuto, errors.New(
		"cover artwork is not a JPEG or PNG image",
	)
}
